### ISSUE TITLE
Take-way

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#119] opened 2017-01-17 02:22 UTC
1.If i view sales history its displaying error pup=over 
![sales history41](https://cloud.githubusercontent.com/assets/20481136/22005519/f17da628-dc89-11e6-9b95-07dedbe9211b.png)

**Comment by GanuM** [comment] 2017-01-17 03:04
duplicate of #63 , close if it is duplicate

**Comment by amarN** [comment] 2017-01-17 08:04
this is duplicate so closed.

**Closed by amarN** 2017-01-17 08:04 UTC
Labels: bug, DAPP, duplicate, Restaurant, Take-away
