### ISSUE TITLE
Reservation(while creating the table reservation then not able to select table.)

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#82] opened 2017-01-14 04:28 UTC
- [ ] while start creating the table reservation the not able to select table.
![aa r](https://cloud.githubusercontent.com/assets/24929491/21952362/acdc04ac-da3f-11e6-9853-38bf7269d0d3.png)

**Comment by GanuM** [comment] 2017-01-17 02:53
@dharwadkarR this seems to be same as #96 , verify and close if it is duplicate

**Comment by GanuM** [comment] 2017-01-27 18:18
duplicate of #47

**Closed by GanuM** 2017-01-27 18:18 UTC
Labels: bug, DAPP, duplicate, Reservation, Restaurant
