### ISSUE TITLE
item

### ISSUE THREAD

**Issue by amarN** [GanuM/profitGuruPOS#28] opened 2017-01-10 11:30 UTC
1. not able to submit in inventory update
2.alignment no proper
3.while creating new item we are not able to submit.
![inventry](https://cloud.githubusercontent.com/assets/24929510/21804676/3aace3e2-d756-11e6-9eae-28ac26e6705a.png)

**Comment by moghribalakrishna** [comment] 2017-01-12 15:54
duplicate of #52

**Closed** 2017-01-13 06:41 UTC
Labels: bug, DAPP, duplicate, Menu Items, Retail
