### ISSUE TITLE
items kit (submit button not work)

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#7] opened 2017-01-05 12:09 UTC
1.while creating items kit submit button not working 
![add kit00](https://cloud.githubusercontent.com/assets/20481136/21680154/e7734c0c-d36d-11e6-9a9f-b9ff44ba1812.png)

**Comment by GanuM** [comment] 2017-01-27 18:20
duplicate of #44

**Closed by GanuM** 2017-01-27 18:20 UTC
Labels: bug, DAPP, items Kit, Retail
