### ISSUE TITLE
item kit(submit button was not working and alignment)

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#51] opened 2017-01-11 18:53 UTC
1.submit button was not working and  alignment problem.
![screenshot_20170111-175205](https://cloud.githubusercontent.com/assets/24931488/21861914/0ae02c02-d85d-11e6-8946-00d7c109c6de.png)

**Comment by GanuM** [comment] 2017-01-27 18:19
duplicate of #44

**Closed by GanuM** 2017-01-27 18:19 UTC
Labels: bug, items Kit, MAPP, Retail, UI
