### ISSUE TITLE
store configurations 

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#126] opened 2017-01-17 14:21 UTC
1.displaying the proper UI 
![ui8](https://cloud.githubusercontent.com/assets/20481136/22023930/4a728780-dcee-11e6-9470-efc1afcaa1d6.png)

**Comment by GanuM** [comment] 2017-01-18 03:07
duplicate of #36

**Comment by amarN** [comment] 2017-01-18 03:46
issued closed

**Closed by amarN** 2017-01-18 03:46 UTC
Labels: bug fixed, DAPP, duplicate, Retail and Restaurant, Store Config
